/**
 * Common city / region tokens. If any token in the place query matches, we treat the query as
 * geographically anchored enough to skip the “add a city” tip.
 */
const GEO_HINT = new Set(
  [
    "london",
    "rome",
    "milan",
    "milano",
    "florence",
    "firenze",
    "venice",
    "venezia",
    "naples",
    "napoli",
    "turin",
    "torino",
    "paris",
    "lyon",
    "marseille",
    "berlin",
    "munich",
    "münchen",
    "hamburg",
    "cologne",
    "köln",
    "frankfurt",
    "stuttgart",
    "amsterdam",
    "rotterdam",
    "brussels",
    "antwerp",
    "zurich",
    "zürich",
    "geneva",
    "basel",
    "vienna",
    "wien",
    "prague",
    "budapest",
    "warsaw",
    "krakow",
    "stockholm",
    "gothenburg",
    "oslo",
    "copenhagen",
    "kobenhavn",
    "helsinki",
    "dublin",
    "edinburgh",
    "glasgow",
    "manchester",
    "liverpool",
    "birmingham",
    "bristol",
    "cardiff",
    "madrid",
    "barcelona",
    "seville",
    "lisbon",
    "porto",
    "athens",
    "istanbul",
    "tokyo",
    "osaka",
    "kyoto",
    "seoul",
    "singapore",
    "sydney",
    "melbourne",
    "brisbane",
    "perth",
    "auckland",
    "wellington",
    "toronto",
    "montreal",
    "vancouver",
    "calgary",
    "ottawa",
    "quebec",
    "nyc",
    "manhattan",
    "brooklyn",
    "queens",
    "bronx",
    "chicago",
    "boston",
    "miami",
    "atlanta",
    "seattle",
    "denver",
    "phoenix",
    "dallas",
    "houston",
    "austin",
    "philadelphia",
    "philly",
    "portland",
    "los",
    "york",
    "francisco",
    "jose",
    "vegas",
    "nashville",
    "orleans",
    "honolulu",
    "downtown",
    "midtown",
    "uptown",
    "soho",
    "chelsea",
    "williamsburg",
    "usa",
    "uk",
    "uae",
    "france",
    "italy",
    "spain",
    "germany",
    "japan",
    "china",
    "india",
    "mexico",
    "canada",
    "australia",
    "ireland",
    "scotland",
    "england",
    "wales",
    "california",
    "texas",
    "florida",
    "colorado",
    "washington",
    "oregon",
    "illinois",
    "massachusetts",
    "georgia",
    "arizona",
    "nevada",
    "hawaii",
  ],
);

function normalizeToken(raw: string): string {
  return raw
    .toLowerCase()
    .replace(/^[^a-z0-9]+/i, "")
    .replace(/[^a-z0-9]+$/i, "");
}

/**
 * True when the Google text query is short enough that adding a city or neighborhood would
 * usually improve Text Search precision (named-venue modes only; caller should gate on query mode).
 */
export function shouldSuggestPlaceDisambiguation(googleTextQuery: string): boolean {
  const words = googleTextQuery.trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) return false;
  if (words.length >= 3) return false;
  if (words.length === 1) return true;
  const a = normalizeToken(words[0]!);
  const b = normalizeToken(words[1]!);
  if (GEO_HINT.has(a) || GEO_HINT.has(b)) return false;
  return true;
}
